from agents.human_agent import HumanAgent
from agents.simple_agent import SimpleAgent
from agents.simple_learning_agent import SimpleLearningAgent
from agents.simple_proba_agent import SimpleProbaAgent
